os: linux
language: node_js
node_js:
  - 12
install:
  - npm ci --ignore-scripts
script:
  - npx nps prepare
  - npx nps publish-client
cache:
  directories:
    - packages/backend/.serverless
    - packages/backend/.webpack
    - packages/client/.linaria-cache
