os: linux
dist: bionic
language: node_js
node_js:
  - 12
jobs:
  include:

    # ----- Setup --------------------------------------------------------------

    # This job will install dependencies and bootstrap the project, but will not
    # run the "prepare" script. It will then stash the state of the project
    # directory in a workspace named "setup".
    - stage: setup
      workspaces:
        create:
          name: setup
          paths:
            - $TRAVIS_BUILD_DIR
      install: npm ci --ignore-scripts
      script: lerna bootstrap


    # ----- Build (Client) -----------------------------------------------------

    # This job will use the "setup" workspace created in the previous job, build
    # the client package, then stash the state of the project directory in a
    # workspace named "build-client".
    - stage: build
      workspaces:
        use: setup
        create:
          name: build-client
          paths:
            - $TRAVIS_BUILD_DIR
      install: skip
      script: npx nps client.build


    # ----- Build (Backend) ----------------------------------------------------

    # This job will use the "setup" workspace created in the previous job, build
    # the backend package, then stash the state of the project directory in a
    # workspace named "build-backend".
    - stage: build
      workspaces:
        use: setup
        # May use this later to publish backend via CI.
        create:
          name: build-backend
          paths:
            - $TRAVIS_BUILD_DIR
      install: skip
      script: npx nps backend.build


    # ----- Deploy Client (inspir.at) ------------------------------------------

    # This job will use the "build-client" workspace created in a previous job
    # to deploy the client to the https://inspir.at Netlify site.
    - stage: deploy-client
      if: branch = master
      workspaces:
        use: build-client
      install: skip
      script: skip
      deploy:
        provider: netlify
        site: $NETLIFY_SITE_ID_INSPIRAT
        auth: $NETLIFY_AUTH_TOKEN
        dir: packages/client/dist
        prod: true
        edge: true


    # ----- Deploy Client (frontlawn.net) --------------------------------------

    # This job will use the "build-client" workspace created in a previous job
    # to deploy the client to the https://frontlawn.net Netlify site.
    - stage: deploy-client
      if: branch = master
      workspaces:
        use: build-client
      script: skip
      install: skip
      deploy:
        provider: netlify
        site: $NETLIFY_SITE_ID_FRONTLAWN
        auth: $NETLIFY_AUTH_TOKEN
        dir: packages/client/dist
        prod: true
        edge: true


    # ----- Publish Chrome Extension -------------------------------------------

    # This job will use the "build-client" workspace created in a previous job
    # to publish the client to the Chrome Web Store.
    - stage: publish-client
      if: branch = master
      workspaces:
        use: build-client
      install: skip
      script: npx nps client.publish
