service:
  name: inspirat
plugins:
  - serverless-webpack
  - serverless-domain-manager

custom:
  stage: ${opt:stage, 'dev'}
  basePaths:
    dev: inspirat-dev
    prod: inspirat

  # Configuration for serverless-domain-manager
  customDomain:
    domainName: aws.frontlawn.net
    # Required when using us-west-1.
    endpointType: regional
    basePath: ${self:custom.basePaths.${self:custom.stage}}
    stage: ${self:custom.stage}
    createRoute53Record: true
    # certificateArn: arn:aws:acm:us-west-1:771590014632:certificate/373dfce9-0c1d-4472-ae03-419370902bf5


# ----- Serverless Compute Provider Configuration ------------------------------

provider:
  name: aws
  runtime: nodejs8.10
  region: us-west-1
  stage: ${self:custom.stage}
  environment:
    STAGE: ${self:custom.stage}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:*
      Resource: arn:aws:dynamodb:*:*:table/inspirat-${self:custom.stage}



# ----- Functions --------------------------------------------------------------

functions:
  # Queries the Unsplash API and adds any new photos from our collection to our
  # DynamoDB table as "partial" records.
  sync-collection:
    events:
      - schedule:
          name: sync-collection-${self:custom.stage}
          description: 'Sync collection from Unsplash.'
          rate: rate(1 hour)
    handler: src/sync-collection.default
    environment:
      UNSPLASH_ACCESS_KEY: ${env:UNSPLASH_ACCESS_KEY}
      UNSPLASH_COLLECTION_ID: ${env:UNSPLASH_COLLECTION_ID}
    timeout: 120

  # Gets a list of all "partial" records from DynamoDB and converts them to
  # "full" records by querying the Unsplash /photo/:photoId API.
  update-records:
    events:
      - schedule:
          name: update-records-${self:custom.stage}
          description: 'Update partial records.'
          rate: rate(1 hour)
    handler: src/update-records.default
    environment:
      UNSPLASH_ACCESS_KEY: ${env:UNSPLASH_ACCESS_KEY}
    timeout: 120

  # Returns all full photo records from our DynamoDB table. This is the only
  # function exposed via API Gateway.
  get-photos:
    events:
      - http:
          method: GET
          path: photos
          cors: true
          origin: '*'
    handler: src/get-photos.default


# ----- CloudFormation Resource Templates --------------------------------------

resources:
  Resources:
    # Development table.
    Inspirat:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        TableName: inspirat-${self:custom.stage}
        AttributeDefinitions:
          -
            AttributeName: id
            AttributeType: S
        KeySchema:
          -
            AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
    # # Production table.
    # InspiratProd:
    #   Type: 'AWS::DynamoDB::Table'
    #   Properties:
    #     TableName: inspirat-prod
    #     AttributeDefinitions:
    #       -
    #         AttributeName: id
    #         AttributeType: S
    #     KeySchema:
    #       -
    #         AttributeName: id
    #         KeyType: HASH
    #     ProvisionedThroughput:
    #       ReadCapacityUnits: 1
    #       WriteCapacityUnits: 1
