name: ci
on:
  - push
  - pull_request
jobs:
  # ----- Build ----------------------------------------------------------------
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      AWS_REGION: ${{ secrets.AWS_REGION }}
      BUCKET_URL: ${{ secrets.BUCKET_URL }}
      UNSPLASH_ACCESS_KEY: ${{ secrets.UNSPLASH_ACCESS_KEY }}
      UNSPLASH_SECRET_KEY: ${{ secrets.UNSPLASH_SECRET_KEY }}
    steps:
      - name: Fetch Repository
        uses: actions/checkout@v2
        with:
          # N.B. Ensures all tags are fetched so we can introspect the
          # repository.
          fetch-depth: 0
      - name: Set-Up Node
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Install Dependencies
        run: npm ci --ignore-scripts && npx lerna bootstrap
      - name: Build Project
        run: npx nps prepare
      - name: Cache Repo State
        uses: actions/cache@v1
        with:
          key: inspirat-${{ github.sha }}
          path: .

  # ----- Deploy Clients -------------------------------------------------------
  deploy:
    name: Deploy Clients
    needs: build
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/master' }}
    steps:
      - name: Fetch Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set-Up Node
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Use Repo Cache
        uses: actions/cache@v1
        with:
          key: inspirat-${{ github.sha }}
          path: .
      - name: frontlawn.net
        uses: netlify/actions/cli@master
        with:
          args: deploy --prod --dir=packages/client/dist
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID_FRONTLAWN }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
      - name: inspir.at
        uses: netlify/actions/cli@master
        with:
          args: deploy --prod --dir=packages/client/dist
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID_INSPIRAT }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}

  # ----- Publish Chrome Extension ---------------------------------------------
  publish:
    name: Publish Extension
    needs: build
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/master' }}
    steps:
      - name: Fetch Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set-Up Node
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Use Repo Cache
        uses: actions/cache@v1
        with:
          key: inspirat-${{ github.sha }}
          path: .
      - name: Publish Extension
        run: npx nps client.publish
